//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spasite.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        internal object[] id;

        public int Id_engineer { get; set; }
        public Nullable<int> Id_employee { get; set; }
        public string Specialization { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
