//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spasite.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        internal int id_exam;
        internal object idcode;

        public int Id_exam { get; set; }
        public DateTime? Date_exam { get; set; }
        public Nullable<int> Id_discipline { get; set; }
        public Nullable<int> Id_student { get; set; }
        public Nullable<int> Id_employee { get; set; }
        public string Auditorium { get; set; }
        public int Estimation { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
        public DateTime? DateOfExam { get; internal set; }
        public object Assessment { get; internal set; }
        public object RegNumber { get; internal set; }
        public object Nunber { get; internal set; }
    }
}
