//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace spasite.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Management_Your_family
    {
        public int Id_management { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
    }
}
